text = (
    ("0.0.1", "Use For Unified Hawa Data."),
    ("0.0.2", "Add build_set_project_params function."),
    ("0.0.3", "Add new inheritance classes."),
    ("0.0.4", "Fix mht data web support."),
    ("0.0.5", "Fix mht student score group error."),
    ("0.0.6", "Fix mro order."),
    ("0.0.7", "Add mht grade name."),
    ("0.1.0", "Filter validity"),
    ("0.1.1", "Revove mht unused students"),
    ("0.1.2", "Use sqlarchemy engine replace mysqlclient conn"),
    ("0.1.3", "Fix local engine"),
    ("0.1.4", "Fix not same data by mht final score"),
    ("0.1.5", "Fix float to int error"),
    ("0.1.6", "Fix special students"),
    ("0.1.7", "Handle link error for db."),
    ("0.1.8", "Fix mysqldb cursor error."),
    ("0.1.9", "Fix redundant async"),
    ("0.2.0", "Add district data"),
    ("0.2.1", "Move gender count data to health."),
    ("0.2.2", "Move health school to health report"),
    ("0.2.3", "Fix cache year data"),
    ("0.2.4", "Filter users when length id <18"),
    ("0.2.5", "Filter users when length id <18 true"),
    ("0.2.6", "Fix rank dis"),
    ("0.2.7", "Fix miss grade"),
    ("0.2.8", "Fix miss grade all"),
    ("0.2.9", "Fix miss grade again"),
    ("0.3.0", "Fix more school when query school"),
    ("0.3.1", "Update replace select *"),
    ("0.3.2", "performance improvement by nickname/username、cronbach_alpha、code_word"),
    ("0.3.3", "performance improvement by grade"),
    ("0.3.4", "up to py3.11"),
)
