text = (
    ("0.0.1", "Use For Unified Hawa Data."),
    ("0.0.2", "Add build_set_project_params function."),
    ("0.0.3", "Add new inheritance classes."),
    ("0.0.4", "Fix mht data web support."),
    ("0.0.5", "Fix mht student score group error."),
    ("0.0.6", "Fix mro order."),
    ("0.0.7", "Add mht grade name."),
    ("0.1.0", "Filter validity"),
    ("0.1.1", "Revove mht unused students"),
    ("0.1.2", "Use sqlarchemy engine replace mysqlclient conn"),
    ("0.1.3", "Fix local engine"),
    ("0.1.4", "Fix not same data by mht final score"),
    ("0.1.5", "Fix float to int error"),
    ("0.1.6", "Fix special students"),
    ("0.1.7", "Handle link error for db."),
    ("0.1.8", "Fix mysqldb cursor error."),
    ("0.1.9", "Fix redundant async"),
    ("0.2.0", "Add district data"),
)
